"""
Django settings for titanpay project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from web3 import Web3
from eth_account.account import Account
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY', "sjhkefkyusfdk")

DEBUG = os.getenv('DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', "*", 'api2.pdva0.xyz', 'api.mippay.xyz', 'api.lumopay.xyz', 'api2.titanpay.me']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'django_extensions',
    "corsheaders",
    'django_otp',
    'django_otp.plugins.otp_totp',
    'two_factor',
    'django.contrib.sites',
    'qrcode',
    'rest_framework',
    'drf_yasg',
    'rest_framework.authtoken',
    'django_filters',
    "django_prometheus",
    'basics',
    'merchant',
    'payments',
    'sms',
    'trade',
    'bots',
    'appeals',
    'usermanagement',
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist"
]

SITE_ID = 1

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware',
    # 'payments.middleware.ProxyVerificationMiddleware',
    # 'payments.middleware.SignatureVerificationMiddleware'
]

ROOT_URLCONF = 'titanpay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'titanpay.wsgi.application'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=20),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=24)
}

if DEBUG:
    DEFAULT_RENDERER_CLASSES = (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    )
else:
    DEFAULT_RENDERER_CLASSES = (
        "rest_framework.renderers.JSONRenderer",
    )

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': DEFAULT_RENDERER_CLASSES,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication'
    ],
    'DATETIME_FORMAT': '%s',
}


CRONJOBS = [
    ('* * * * *', 'trade.tasks.update_all','>> /var/log/cron.log 2>&1'),
]


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


LOCAL = os.getenv('LOCAL', 'false').lower() == 'true'
if LOCAL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.getenv('MAIN_DB_NAME'),
            'USER': os.getenv('MAIN_DB_USER'),
            'PASSWORD': os.getenv('MAIN_DB_PASSWORD'),
            'HOST': os.getenv('MAIN_DB_HOST'),
            'PORT': int(os.getenv('MAIN_DB_PORT', 5432)),
        }
    }
    # DATABASES["default"]["ENGINE"] = "django_prometheus.db.backends.postgresql"
PROMETHEUS_EXPORT_MIGRATIONS = os.getenv("PROMETHEUS_EXPORT_MIGRATIONS", "true").lower() == "true"
if not LOCAL:
    CACHES = {
        'default': {
            'BACKEND': 'django_prometheus.cache.backends.redis.RedisCache',
            'LOCATION': [
                'redis://{}'.format(os.getenv('REDIS_HOST', 'localhost:6379/1')),
            ],
        }
    }
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'
if not LOCAL:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "console": {
                'level': 'DEBUG',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        "formatters": {
            "verbose": {
                "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s (%(filename)s:%(lineno)d)",
                "datefmt": "%H:%M:%S.%s",
            },
        },
        "root": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        "loggers": {
            "django.access": {
                "handlers": ["console"],
                "level": "ERROR",
                "propagate": False,
            },
            "web3": {
                "handlers": ["console"],
                "level": "WARNING",
                "propagate": False,
            },
            "payin.trace": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_MEMORY_SIZE = 3 * 1024 * 1024  # 3 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 3 * 1024 * 1024  # 3 MB

SYSTEM_INTERVAL_VALUE = 3 * 60 * 60  # 3 hours
CLIENT_SUCCESS_RATE = 0.2
ARBITRAGE_LIMIT = 3
# При арбитраже ставить PaymentDetailsGroup.status=4 (блок роутинга на эту группу).
# По умолчанию выключено — реквизит/PSP-группа остаётся доступной для новых заявок.
ARBITRAGE_BLOCK_PAYMENT_GROUP = os.getenv('ARBITRAGE_BLOCK_PAYMENT_GROUP', 'false').lower() in (
    'true',
    '1',
    'yes',
)
RATE_UPD_TIME = 60
LOW_DEPOSIT_LEVEL = 1000
SBER_NAME = "Sber"
TBANK_NAME = "Tinkoff"
SBERPAY_NAME = "SberPay"
SBP_NAME = "SBP"
SBERDEP_NAME = "SberDep"
OTP_NAME = "OTP"
ALFA_NAME = "Alfa"
INTERBANK_NAME = "Interbank"
UPI_INTENT_NAME = os.getenv('FAIRPAY_PAYMENT_SYSTEM_NAME', 'UPI Intent')
C2C_NAME='C2C'

PAYMENT_PAGE_URL = os.getenv('PAYMENT_PAGE_URL')
SMS_ENDPOINT = os.getenv('SMS_ENDPOINT')
CRYPTO_URL = os.getenv('CRYPTO_URL')
EMERGENCY_URL = os.getenv('EMERGENCY_URL')
S3_ENDPOINT = os.getenv('S3_ENDPOINT')
ACCESS_KEY = os.getenv('ACCESS_KEY')
SECRET_S3_KEY = os.getenv('SECRET_S3_KEY')
BUCKET_NAME = os.getenv('BUCKET_NAME')

# Telegram appeal bot (отправка чеков в чат провайдера)
APPEAL_TELEGRAM_BOT_TOKEN = os.getenv('APPEAL_TELEBOT_TOKEN', '')

# Публичный базовый URL API (экспорт, ссылки в логах; переопределите через PUBLIC_API_URL)
PUBLIC_API_URL = os.getenv('PUBLIC_API_URL', 'https://api.avapay.net')

# FairPay PSP (колбек: {PUBLIC_API_URL}/api/v1/webhooks/psp/fairpay/)
FAIRPAY_API_BASE = os.getenv('FAIRPAY_API_BASE', 'https://api.fairpay.cc').rstrip('/')
FAIRPAY_API_TOKEN = os.getenv('FAIRPAY_API_TOKEN', '')
FAIRPAY_METHOD_ID = os.getenv('FAIRPAY_METHOD_ID', 'cascade_intent')
FAIRPAY_INTEGRATION = os.getenv('FAIRPAY_INTEGRATION', 'deeplink')
FAIRPAY_TRADER_USERNAME = os.getenv('FAIRPAY_TRADER_USERNAME', 'fairpay_agg')
# Имя PaymentSystem в БД для FairPay / UPI Intent — должно совпадать с route() в trade/routing/base.py
UPI_INTENT_NAME = os.getenv('UPI_INTENT_NAME') or os.getenv('FAIRPAY_PAYMENT_SYSTEM_NAME') or 'UPI Intent'

# ExpayOne PSP (колбек: {PUBLIC_API_URL}/api/v1/webhooks/psp/expayone/)
EXPAYONE_API_BASE = os.getenv('EXPAYONE_API_BASE', 'https://expay.one').rstrip('/')
EXPAYONE_ACCESS_TOKEN = os.getenv('EXPAYONE_ACCESS_TOKEN', 'xrijbtevweyjmnynqdwnjqnf8kb2od7w')
EXPAYONE_MERCHANT_ID = os.getenv('EXPAYONE_MERCHANT_ID', '5dc170e2-9914-4c63-b7f0-5a1680a5f56f')
EXPAYONE_TRADER_USERNAME = os.getenv('EXPAYONE_TRADER_USERNAME', 'expayone1')
# JSON: {"Sber": "sberbank", "SBP": "sbp"} — код payment_gateway в ExpayOne
EXPAYONE_GATEWAY_MAP = os.getenv('EXPAYONE_GATEWAY_MAP', '')
# C2C/KZT: POST /api/h2h/order с currency=kzt (без payment_gateway), см. доку ExpayOne
EXPAYONE_USE_CURRENCY_FOR_C2C = os.getenv('EXPAYONE_USE_CURRENCY_FOR_C2C', 'true').lower() in ('true', '1', 'yes')

# GiPay PSP (gipay.org, Aggrepay API v2, колбек: {PUBLIC_API_URL}/api/v1/webhooks/psp/gipay/)
GIPAY_API_BASE = os.getenv('GIPAY_API_BASE', 'https://gipay.org').rstrip('/')
GIPAY_MERCHANT_ID = os.getenv('GIPAY_MERCHANT_ID', '')
GIPAY_SECRET_KEY = os.getenv('GIPAY_SECRET_KEY', '')
GIPAY_API_KEY = os.getenv('GIPAY_API_KEY', '')
GIPAY_TRADER_USERNAME = os.getenv('GIPAY_TRADER_USERNAME', 'gipay1')
GIPAY_PAYIN_METHOD = os.getenv('GIPAY_PAYIN_METHOD', 'tgkz')
# JSON: {"C2CKZT":"tgkz","C2C":"tgkz"} — method в POST /api/v2/payments (оба PS → tgkz)
GIPAY_PAYIN_METHOD_MAP = os.getenv('GIPAY_PAYIN_METHOD_MAP', '{"C2CKZT":"tgkz","C2C":"tgkz"}')
GIPAY_ASSET_OR_BANK = os.getenv('GIPAY_ASSET_OR_BANK', '')
GIPAY_DEFAULT_PAYER_IP = os.getenv('GIPAY_DEFAULT_PAYER_IP', '127.0.0.1')
GIPAY_PAYER_USER_ID_FROM_CLIENT = os.getenv('GIPAY_PAYER_USER_ID_FROM_CLIENT', 'false').lower() in ('true', '1', 'yes')
GIPAY_WEBHOOK_SKIP_VERIFY = os.getenv('GIPAY_WEBHOOK_SKIP_VERIFY', 'false').lower() in ('true', '1', 'yes')
# Доп. ключи для проверки Signature (через запятую), если в ЛК отдельный signing secret
GIPAY_WEBHOOK_SIGNING_KEYS = os.getenv('GIPAY_WEBHOOK_SIGNING_KEYS', '')

# VisionX Pay PSP (https://api.visionxpay.club, колбек: {PUBLIC_API_URL}/api/v1/webhooks/psp/visionx/)
VISIONX_API_BASE = os.getenv('VISIONX_API_BASE', 'https://api.visionxpay.club').rstrip('/')
VISIONX_API_KEY = os.getenv('VISIONX_API_KEY', '')
VISIONX_SECRET_KEY = os.getenv('VISIONX_SECRET_KEY', '')
VISIONX_TRADER_USERNAME = os.getenv('VISIONX_TRADER_USERNAME', 'visionx1')
# JSON: {"C2CKZT":"halyk","C2C":"halyk"} — paymentMethod (код банка), null = любой
VISIONX_PAYIN_METHOD_MAP = os.getenv('VISIONX_PAYIN_METHOD_MAP', '')
VISIONX_PAYIN_METHOD = os.getenv('VISIONX_PAYIN_METHOD', '')
# JSON: {"C2CKZT":"TO_CARD","C2C":"TO_CARD"} — paymentOption, null = любой
VISIONX_PAYIN_OPTION_MAP = os.getenv('VISIONX_PAYIN_OPTION_MAP', '{"C2CKZT":"TO_CARD","C2C":"TO_CARD"}')
VISIONX_PAYIN_OPTION = os.getenv('VISIONX_PAYIN_OPTION', 'TO_CARD')
VISIONX_PAYER_USER_ID_FROM_CLIENT = os.getenv('VISIONX_PAYER_USER_ID_FROM_CLIENT', 'false').lower() in ('true', '1', 'yes')
VISIONX_WEBHOOK_SKIP_VERIFY = os.getenv('VISIONX_WEBHOOK_SKIP_VERIFY', 'false').lower() in ('true', '1', 'yes')

# PayPlat PSP (https://payplat.su, колбек: {PUBLIC_API_URL}/api/v1/webhooks/psp/payplat/)
PAYPLAT_API_BASE = os.getenv('PAYPLAT_API_BASE', 'https://payplat.su/test/api').rstrip('/')
PAYPLAT_SHOP_ID = os.getenv('PAYPLAT_SHOP_ID', '')
PAYPLAT_SECRET_KEY = os.getenv('PAYPLAT_SECRET_KEY', '')
PAYPLAT_TRADER_USERNAME = os.getenv('PAYPLAT_TRADER_USERNAME', 'payplat1')
PAYPLAT_TEST_PS_NAME = os.getenv('PAYPLAT_TEST_PS_NAME', 'C2CKZTTEST')
# JSON: requisite_type для PayPlat (h2h + payer=kz → сумма в тенге)
PAYPLAT_REQUISITE_TYPE_MAP = os.getenv(
    'PAYPLAT_REQUISITE_TYPE_MAP',
    '{"C2C":"h2h","C2CKZT":"h2h","C2CKZTTEST":"h2h"}',
)
PAYPLAT_REQUISITE_TYPE = os.getenv('PAYPLAT_REQUISITE_TYPE', 'h2h')
PAYPLAT_BANK_MAP = os.getenv('PAYPLAT_BANK_MAP', '')
PAYPLAT_BANK = os.getenv('PAYPLAT_BANK', '')
PAYPLAT_TARIFF = os.getenv('PAYPLAT_TARIFF', 'PRIMARY')
# JSON: коридор плательщика — kz = сумма в тенге, ru = в рублях (документация PayPlat)
PAYPLAT_PAYER_MAP = os.getenv(
    'PAYPLAT_PAYER_MAP',
    '{"C2C":"kz","C2CKZT":"kz","C2CKZTTEST":"kz"}',
)
PAYPLAT_PAYER = os.getenv('PAYPLAT_PAYER', 'kz')
PAYPLAT_CONTRAGENT_FROM_CLIENT = os.getenv('PAYPLAT_CONTRAGENT_FROM_CLIENT', 'false').lower() in ('true', '1', 'yes')
PAYPLAT_WEBHOOK_SKIP_VERIFY = os.getenv('PAYPLAT_WEBHOOK_SKIP_VERIFY', 'false').lower() in ('true', '1', 'yes')

# JSON: приоритет PSP в каскаде (меньше = раньше). Не меняет TraderTeamRates.mdr_in (комиссию трейдера).
PSP_ROUTING_PRIORITY_MAP = os.getenv(
    'PSP_ROUTING_PRIORITY_MAP',
    '{"payplat1": 1, "gipay1": 2}',
)

# Protocol PSP (prot0col.com, колбек: {PUBLIC_API_URL}/api/v1/webhooks/psp/protocol/)
PROTOCOL_API_BASE = os.getenv('PROTOCOL_API_BASE', 'https://prot0col.com').rstrip('/')
PROTOCOL_MERCHANT_ID = os.getenv('PROTOCOL_MERCHANT_ID', '')
PROTOCOL_SECRET_KEY = os.getenv('PROTOCOL_SECRET_KEY', '')
PROTOCOL_TRADER_USERNAME = os.getenv('PROTOCOL_TRADER_USERNAME', 'protocol1')
# Отдельная PaymentSystem в БД: лимиты 1000–10000 KZT, курс Binance/Halyk
PROTOCOL_C2C_NAME = os.getenv('PROTOCOL_C2C_NAME', 'C2CKZT')
PROTOCOL_PAYIN_METHOD = os.getenv('PROTOCOL_PAYIN_METHOD', 'c2ckz')
PROTOCOL_ASSET_OR_BANK = os.getenv('PROTOCOL_ASSET_OR_BANK', '')
PROTOCOL_DEFAULT_PAYER_IP = os.getenv('PROTOCOL_DEFAULT_PAYER_IP', '127.0.0.1')
PROTOCOL_API_KEY = os.getenv('PROTOCOL_API_KEY', '374|NZRwEhxoiTWAhjUNx2PetIjYQeXJzTLbjza1nwNEf540f66d')
# Binance P2P payTypes для Halyk (см. GET /api/v2/banks?currency=KZT)
PROTOCOL_BINANCE_PAY_TYPE = os.getenv('PROTOCOL_BINANCE_PAY_TYPE', 'HalykBank')

# Bitzone PSP (колбек: {PUBLIC_API_URL}/api/v1/webhooks/psp/bitzone/)
BITZONE_API_BASE = os.getenv('BITZONE_API_BASE', 'https://api.bitzone.space').rstrip('/')
BITZONE_API_KEY = os.getenv('BITZONE_API_KEY', '')
BITZONE_TRADER_USERNAME = os.getenv('BITZONE_TRADER_USERNAME', 'bitzone1')
# method: card, sbp, cross_card, cross_sbp, … — см. https://developers.bitzone.space/docs/pay-in/
BITZONE_PAYIN_METHOD = os.getenv('BITZONE_PAYIN_METHOD', 'cross_card')
BITZONE_BANK = os.getenv('BITZONE_BANK', '')
BITZONE_DEFAULT_PAYER_IP = os.getenv('BITZONE_DEFAULT_PAYER_IP', '127.0.0.1')
BITZONE_SIGN_OUTBOUND = os.getenv('BITZONE_SIGN_OUTBOUND', 'true').lower() in ('true', '1', 'yes')
# Опционально, если провайдер когда-либо выдаст отдельный secret (сейчас — только BITZONE_API_KEY)
BITZONE_WEBHOOK_SECRET = os.getenv('BITZONE_WEBHOOK_SECRET', '')
# Доп. ключи для проверки x-signature (через запятую), если в ЛК отдельный signing secret
BITZONE_WEBHOOK_SIGNING_KEYS = os.getenv('BITZONE_WEBHOOK_SIGNING_KEYS', '')
# Только для отладки на staging — НЕ включать на prod
BITZONE_WEBHOOK_SKIP_VERIFY = os.getenv('BITZONE_WEBHOOK_SKIP_VERIFY', 'false').lower() in ('true', '1', 'yes')
BITZONE_WEBHOOK_DEBUG = os.getenv('BITZONE_WEBHOOK_DEBUG', 'false').lower() in ('true', '1', 'yes')
BITZONE_PAYER_USER_ID_FROM_CLIENT = os.getenv('BITZONE_PAYER_USER_ID_FROM_CLIENT', 'false').lower() in ('true', '1', 'yes')

# PlutusPay PSP (https://plutuspay.top/docs, колбек: {PUBLIC_API_URL}/api/v1/webhooks/psp/plutus/)
PLUTUS_API_BASE = os.getenv('PLUTUS_API_BASE', 'https://plutuspay.top').rstrip('/')
PLUTUS_API_KEY = os.getenv('PLUTUS_API_KEY', '')
PLUTUS_TRADER_USERNAME = os.getenv('PLUTUS_TRADER_USERNAME', 'plutus1')
PLUTUS_DEFAULT_PAYMETHOD = os.getenv('PLUTUS_DEFAULT_PAYMETHOD', 'c2c')
# JSON: {"C2C":"c2c","C2CKZT":"c2c"} — paymethod в create pay-in
PLUTUS_PAYMETHOD_MAP = os.getenv('PLUTUS_PAYMETHOD_MAP', '')
PLUTUS_PAYIN_TIMEOUT = int(os.getenv('PLUTUS_PAYIN_TIMEOUT', '900') or 900)
PLUTUS_CONTRAGENT = os.getenv('PLUTUS_CONTRAGENT', 'false').lower() in ('true', '1', 'yes')
# Тестовая PS только Plutus (shell_setup_plutus_c2ckzttest_routing.py)
PLUTUS_TEST_PS_NAME = os.getenv('PLUTUS_TEST_PS_NAME', 'C2CKZTTEST')

# Syndicate Pay PSP (https://api.syndicate-pay.com, колбек: {PUBLIC_API_URL}/api/v1/webhooks/psp/syndicate/)
SYNDICATE_API_BASE = os.getenv('SYNDICATE_API_BASE', 'https://api.syndicate-pay.com').rstrip('/')
SYNDICATE_MERCHANT_ID = os.getenv('SYNDICATE_MERCHANT_ID', '')
SYNDICATE_MERCHANT_LOGIN = os.getenv('SYNDICATE_MERCHANT_LOGIN', '')
SYNDICATE_API_KEY = os.getenv('SYNDICATE_API_KEY', '')
SYNDICATE_TRADER_USERNAME = os.getenv('SYNDICATE_TRADER_USERNAME', 'syndicate1')
# JSON: переопределения к payments/data/syndicate_banks.json (полный каталог из xlsx)
SYNDICATE_BANK_MAP = os.getenv('SYNDICATE_BANK_MAP', '')
SYNDICATE_DEFAULT_BANK = os.getenv('SYNDICATE_DEFAULT_BANK', 'any-bank')
SYNDICATE_WEBHOOK_SKIP_VERIFY = os.getenv('SYNDICATE_WEBHOOK_SKIP_VERIFY', 'false').lower() in ('true', '1', 'yes')

# BotonPay PSP (https://botonpay.org/api-docs) — pay-in deals, KZT transgran / multi-fiat
BOTONPAY_API_BASE = os.getenv('BOTONPAY_API_BASE', 'https://botonpay.org/api/public/v1').rstrip('/')
BOTONPAY_API_KEY = os.getenv('BOTONPAY_API_KEY', '')
BOTONPAY_WEBHOOK_SECRET = os.getenv('BOTONPAY_WEBHOOK_SECRET', '')
BOTONPAY_TRADER_USERNAME = os.getenv('BOTONPAY_TRADER_USERNAME', 'botonpay1')
BOTONPAY_WEBHOOK_SKIP_VERIFY = os.getenv('BOTONPAY_WEBHOOK_SKIP_VERIFY', 'false').lower() in ('true', '1', 'yes')
BOTONPAY_TEST_PS_NAME = os.getenv('BOTONPAY_TEST_PS_NAME', 'C2CKZTTEST')

# Melbet KZT ledger: usernames with C2CKZT settlement (prod + melbet_test sandbox)
MELBET_KZT_USERNAMES = os.getenv('MELBET_KZT_USERNAMES', 'melbet,melbet_test')
# Staging: force C2CKZT pay-in routing to this trader (non-PSP local test)
MELBET_KZT_TEST_TRADER_USERNAME = os.getenv('MELBET_KZT_TEST_TRADER_USERNAME', '')
# Melbet redirect: probe nearby amounts when routing/PSP cascade fails (KZT step e.g. ±20)
MELBET_AMOUNT_PROBE_ENABLED = os.getenv('MELBET_AMOUNT_PROBE_ENABLED', 'true').lower() in ('1', 'true', 'yes')
MELBET_AMOUNT_PROBE_DELTAS = os.getenv('MELBET_AMOUNT_PROBE_DELTAS', '20,-20,50,-50,100,-100')
MELBET_AMOUNT_PROBE_MAX_EXTRA = int(os.getenv('MELBET_AMOUNT_PROBE_MAX_EXTRA', '6'))
MELBET_AMOUNT_PROBE_RANDOMIZE = os.getenv('MELBET_AMOUNT_PROBE_RANDOMIZE', 'true').lower() in ('1', 'true', 'yes')



# Concored / ProcessorCore PSP
CONCORDED_API_BASE = os.getenv('CONCORDED_API_BASE', '').rstrip('/')
CONCORDED_TRADER_USERNAME = os.getenv('CONCORDED_TRADER_USERNAME', 'concored_mmk')
CONCORDED_KBZPAY_TOKEN = os.getenv('CONCORDED_KBZPAY_TOKEN', '')
CONCORDED_WAVEPAY_TOKEN = os.getenv('CONCORDED_WAVEPAY_TOKEN', '')
# JSON override: {"KBZPay": "jwt...", "WavePay": "jwt..."}
CONCORDED_TOKEN_MAP = os.getenv('CONCORDED_TOKEN_MAP', '')
# JSON: {"KBZPay": "<paymentMethod code from Concored>", "WavePay": "..."} — MID-0000011 / MID-0000012
CONCORDED_PAYMENT_METHOD_MAP = os.getenv('CONCORDED_PAYMENT_METHOD_MAP', '')
# Множитель суммы в minor units (MMK обычно 1)
CONCORDED_AMOUNT_MINOR_FACTOR = int(os.getenv('CONCORDED_AMOUNT_MINOR_FACTOR', '1'))
CONCORDED_KBZPAY_PS_NAME = os.getenv('CONCORDED_KBZPAY_PS_NAME', 'KBZPay')
CONCORDED_WAVEPAY_PS_NAME = os.getenv('CONCORDED_WAVEPAY_PS_NAME', 'WavePay')
C2CMMK_NAME = os.getenv('C2CMMK_NAME', 'C2CMMK')

# PayMap PSP (API v2, KZT; docs http://docs.paymap.me; API host europe.paymap.me; callback /api/v1/webhooks/psp/paymap/)
PAYMAP_API_BASE = os.getenv('PAYMAP_API_BASE', 'https://europe.paymap.me').rstrip('/')
PAYMAP_API_KEY = os.getenv('PAYMAP_API_KEY', '')
PAYMAP_TRADER_USERNAME = os.getenv('PAYMAP_TRADER_USERNAME', 'paymap_kzt')
PAYMAP_DEFAULT_INVOICE_TYPE = os.getenv('PAYMAP_DEFAULT_INVOICE_TYPE', 'CARD')
PAYMAP_INVOICE_TYPE_MAP = os.getenv('PAYMAP_INVOICE_TYPE_MAP', '')
PAYMAP_TARGET_BANK_MAP = os.getenv('PAYMAP_TARGET_BANK_MAP', '')
PAYMAP_INVOICE_LIFETIME_MINUTES = int(os.getenv('PAYMAP_INVOICE_LIFETIME_MINUTES', '15'))
PAYMAP_CANCEL_ON_DECLINE = os.getenv('PAYMAP_CANCEL_ON_DECLINE', '').strip().lower() in ('1', 'true', 'yes')

# Playments PSP (TRY bank transfer H2H pay-in / pay-out)
PLAYMENTS_API_BASE = os.getenv('PLAYMENTS_API_BASE', 'https://api.playments.world').rstrip('/')
PLAYMENTS_MERCHANT_GROUP_ID = os.getenv('PLAYMENTS_MERCHANT_GROUP_ID', '')
PLAYMENTS_MERCHANT_ID = os.getenv('PLAYMENTS_MERCHANT_ID', '')
PLAYMENTS_SECRET_KEY = os.getenv('PLAYMENTS_SECRET_KEY', '')
PLAYMENTS_WEBHOOK_SECRET = os.getenv('PLAYMENTS_WEBHOOK_SECRET', '')
PLAYMENTS_TRADER_USERNAME = os.getenv('PLAYMENTS_TRADER_USERNAME', 'playments1')
PLAYMENTS_C2C_NAME = os.getenv('PLAYMENTS_C2C_NAME', 'C2CTRY')
PLAYMENTS_DEFAULT_CLIENT_IP = os.getenv('PLAYMENTS_DEFAULT_CLIENT_IP', '127.0.0.1')
PLAYMENTS_DEPOSIT_CALLBACK_URL = os.getenv('PLAYMENTS_DEPOSIT_CALLBACK_URL', '')
PLAYMENTS_WITHDRAWAL_CALLBACK_URL = os.getenv('PLAYMENTS_WITHDRAWAL_CALLBACK_URL', '')
_playments_raw_secret = os.getenv('PLAYMENTS_USE_RAW_SECRET', '').strip().lower()
PLAYMENTS_USE_RAW_SECRET = False
C2CTRY_NAME = os.getenv('C2CTRY_NAME', 'C2CTRY')
# Comma-separated trader usernames: skip auto liveness (status 5) in cron, like virtual PSP traders
LIVENESS_EXEMPT_TRADER_USERNAMES = os.getenv('LIVENESS_EXEMPT_TRADER_USERNAMES', '')


# CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'https://p2p-platform.lumopay.io',
    'http://p2p-platform.lumopay.io',
    'https://api.mippay.xyz',
    'http://api.mippay.xyz',
    # 'https://platform.pdva0.xyz',
    # 'http://platform.pdva0.xyz',
    'https://api2.pdva0.xyz',
    'http://api2.pdva0.xyz',
    'https://api2.titanpay.me',
    'http://api2.titanpay.me',
    'https://gate.titanpay.me',
    'http://gate.titanpay.me',
    'https://pay.safesolutions.click',
    'http://pay.safesolutions.click',
    'https://payment.safesolutions.click',
    'http://payment.safesolutions.click',
    'https://payments.safesolutions.click',
    'http://payments.safesolutions.click',
    'https://avapay.net',
    'https://api.avapay.net'
]

CORS_ALLOW_HEADERS = ('content-disposition', 'accept-encoding', 'access-control-allow-origin',
                      'content-type', 'accept', 'origin', 'authorization')

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://localhost:8080',
    'https://api.mippay.xyz',
    'https://api.lumopay.io',
    'https://go.lumopay.io',
    'https://gate.lumopay.io',
    'https://p2p-platform.lumopay.io',
    'https://platform.pdva0.xyz',
    'https://gate.pdva0.xyz',
    'https://api2.pdva0.xyz',
    'https://platform.titanpay.me',
    'https://gate.titanpay.me',
    'https://api2.titanpay.me',
    'https://avapay.net',
    'https://api.avapay.net'
]

ADMINS = [
    ('admin', 'admin@admin.com'),
]

DEFAULT_ADMIN_PASSWORD = os.getenv('DEFAULT_ADMIN_PASSWORD', 'admin')
STATIC_URL = "/static/"
STATIC_ROOT = "/app/staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = "/app/media"


CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
CORS_ALLOW_HEADERS = ['*']



# Публичный базовый URL API (экспорт, ссылки в логах; переопределите через PUBLIC_API_URL)
PUBLIC_API_URL = os.getenv('PUBLIC_API_URL', 'https://api.avapay.net')

# FairPay PSP (колбек: {PUBLIC_API_URL}/api/v1/webhooks/psp/fairpay/)
FAIRPAY_API_BASE = os.getenv('FAIRPAY_API_BASE', 'https://api.fairpay.cc').rstrip('/')
FAIRPAY_API_TOKEN = os.getenv('FAIRPAY_API_TOKEN', 'ded346ef-e9d5-4fab-9831-2b5063b3a5d0')
FAIRPAY_METHOD_ID = os.getenv('FAIRPAY_METHOD_ID', 'cascade_intent')
FAIRPAY_INTEGRATION = os.getenv('FAIRPAY_INTEGRATION', 'deeplink')
FAIRPAY_TRADER_USERNAME = os.getenv('FAIRPAY_TRADER_USERNAME', 'fairpay_agg')
