# Generated by Django 5.0.6 on 2024-07-07 22:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('not-found', 'Not Found'), ('wrong-state', 'Wrong State')], default='pending', max_length=11)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.paymentdetailsgroup')),
            ],
        ),
    ]
