# Generated by Django 5.0.6 on 2024-07-13 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0004_alter_paymentdetails_phone'),
        ('sms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basics.trader')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traderdevice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
