# Generated by Django 5.0.6 on 2024-07-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_traderdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('not-found', 'Not Found'), ('red-block', 'Red Block'), ('fz-block', 'FZ Block'), ('compr-block', 'Compromise Block'), ('wrong-state', 'Wrong State')], default='pending', max_length=11),
        ),
    ]
