# Generated by Django 5.0.6 on 2024-07-07 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basics', '0001_initial'),
        ('merchant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('telegram', models.CharField(default=None, max_length=64, null=True)),
                ('phone', models.CharField(default=None, max_length=64, null=True)),
                ('is_head', models.BooleanField(default=False)),
                ('controlled_merchants', models.ManyToManyField(to='merchant.merchant')),
                ('controlled_teams', models.ManyToManyField(to='basics.traderteam')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
