http:
  middlewares:
    cors:
      headers:
        accessControlAllowMethods:
          - "GET"
          - "OPTIONS"
          - "PUT"
          - "POST"
          - "DELETE"
          - "PATCH"
        accessControlAllowOriginList:
          - "https://avapay.net"
          - "http://avapay.net"
          - "https://avapay.cc"
          - "http://avapay.cc"
          - "https://www.avapay.cc"
          - "http://www.avapay.cc"
        accessControlAllowHeaders:
          - "Authorization"
          - "Content-Type"
          - "Accept"
          - "Origin"
          - "X-Requested-With"
        accessControlAllowCredentials: true
        accessControlMaxAge: 3600
        addVaryHeader: true
