# Generated by Django 5.0.6 on 2024-07-07 22:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('telegram', models.CharField(default=None, max_length=64, null=True)),
                ('phone', models.CharField(default=None, max_length=64, null=True)),
                ('balance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='available_merchant', to='basics.balance')),
                ('frozen_balance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='frozen_merchant', to='basics.balance')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.language')),
                ('payment_systems', models.ManyToManyField(to='basics.paymentsystem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantSolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('mdr_in', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mdr_out', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ftd', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchant')),
                ('payment_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.paymentsystem')),
                ('traffic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.traffictype')),
            ],
        ),
    ]
