# Generated by Django 5.0.6 on 2024-07-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_submerchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantsolution',
            name='autoclose_arbitrage',
            field=models.BooleanField(default=False),
        ),
    ]
