# Generated by Django 5.0.6 on 2024-09-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_merchantsolution_autoclose_arbitrage'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantsolution',
            name='max_limit_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='merchantsolution',
            name='max_limit_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='merchantsolution',
            name='min_limit_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='merchantsolution',
            name='min_limit_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
    ]
