# Generated by Django 5.0.6 on 2024-07-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payout_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeys',
            name='whitelist_ips',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='apikeys',
            name='whitelist_on',
            field=models.BooleanField(default=False),
        ),
    ]
