# Generated by Django 5.0.6 on 2024-07-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_apikeys_whitelist_ips_apikeys_whitelist_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='payin',
            name='recalculated',
            field=models.BooleanField(default=False),
        ),
    ]
