# Generated by Django 5.0.6 on 2024-07-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payin_recalculated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='devices',
            field=models.ManyToManyField(blank=True, null=True, to='payments.device'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
