# Generated by Django 5.0.6 on 2024-07-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_client_devices_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payin',
            name='failed_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payin',
            name='success_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
