# Generated by Django 5.0.6 on 2024-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payin_failed_url_alter_payin_success_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='failed_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='success_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
