# Generated by Django 5.0.6 on 2024-07-07 22:46

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=32)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('symbol', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='English', max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraderTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('rate_in', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rate_out', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='TrafficType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('risk_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetailsGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('owner', models.CharField(default='', max_length=255)),
                ('min_amount_out', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_amount_out', models.DecimalField(decimal_places=2, default=1000000, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('in_active', models.BooleanField(default=True)),
                ('out_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('limit_per_period', models.DecimalField(decimal_places=2, default=Decimal('300000'), max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_volume', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_out_volume', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.currency')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('sberpay_enabled', models.BooleanField(default=False)),
                ('sbp_enabled', models.BooleanField(default=False)),
                ('card_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_card_number', message='Enter a valid card number in format of 16 digits', regex='^d{16}$')])),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number', regex='^\\+79d{9}$')])),
                ('deposit_number', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_deposit_number', message='Enter a valid deposit number', regex='^d{4}$')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='basics.paymentdetailsgroup')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('expired_time_in', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('expired_time_out', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('constrain_time_out', models.DurationField(default=datetime.timedelta(seconds=14400))),
                ('required_fields', models.JSONField()),
                ('usdt_exchange_rate', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_update', models.IntegerField(default=0)),
                ('in_on', models.BooleanField(default=True)),
                ('out_on', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.currency')),
            ],
        ),
        migrations.AddField(
            model_name='paymentdetailsgroup',
            name='payment_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.paymentsystem'),
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('telegram', models.CharField(default=None, max_length=64, null=True)),
                ('phone', models.CharField(default=None, max_length=64, null=True)),
                ('is_boss', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
                ('balance_usdt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='available', to='basics.balance')),
                ('boss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.trader')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.currency')),
                ('frozen_balance_usdt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trader_frozen', to='basics.balance')),
                ('language', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='basics.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.traderteam')),
            ],
        ),
        migrations.AddField(
            model_name='paymentdetailsgroup',
            name='trader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.trader'),
        ),
        migrations.AddField(
            model_name='paymentdetailsgroup',
            name='allowed_traffic',
            field=models.ManyToManyField(to='basics.traffictype'),
        ),
    ]
