# Generated by Django 5.0.6 on 2024-07-08 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='card_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_card_number', message='Enter a valid card number in format of 16 digits', regex='^\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='deposit_number',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_deposit_number', message='Enter a valid deposit number', regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number', regex='^\\+79\\d{9}$')]),
        ),
    ]
