# Generated by Django 5.0.6 on 2024-07-09 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_alter_paymentdetails_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
