# Generated by Django 5.0.6 on 2024-07-13 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_alter_paymentdetails_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number', regex='^\\+79\\d{9}$')]),
        ),
    ]
