# Generated by Django 5.0.6 on 2024-07-15 22:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0004_alter_paymentdetails_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traderteam',
            name='teamlead_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='TeamLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('telegram', models.CharField(default=None, max_length=64, null=True)),
                ('phone', models.CharField(default=None, max_length=64, null=True)),
                ('balance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamlead', to='basics.balance')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='traderteam',
            name='teamlead',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.teamlead'),
        ),
    ]
