# Generated by Django 5.0.6 on 2024-07-30 18:15

import datetime
import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0005_traderteam_teamlead_percentage_teamlead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetailsgroup',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='paymentsystem',
            name='arbitrage_time_in',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
        migrations.AddField(
            model_name='paymentsystem',
            name='auto_close_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('-1'), max_digits=32),
        ),
        migrations.AddField(
            model_name='paymentsystem',
            name='confirm_time_out',
            field=models.DurationField(default=datetime.timedelta(seconds=600)),
        ),
        migrations.AddField(
            model_name='trader',
            name='super_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trader',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetailsgroup',
            name='status',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
