# Generated by Django 5.0.6 on 2024-08-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0006_paymentdetailsgroup_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystem',
            name='sbp_compatible',
            field=models.BooleanField(default=True),
        ),
    ]
