# Generated by Django 5.0.6 on 2024-08-14 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0007_paymentsystem_sbp_compatible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_card_number', message='Enter a valid card number in format of 16 digits', regex='^\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='deposit_number',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='invalid_deposit_number', message='Enter a valid deposit number', regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number', regex='^\\+79\\d{9}$')]),
        ),
        migrations.AddConstraint(
            model_name='paymentdetails',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('group', 'deposit_number'), name='unique_active_deposit_number_per_group'),
        ),
    ]
