# Generated by Django 5.0.6 on 2024-09-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0008_alter_paymentdetails_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetailsgroup',
            name='deposit_number_on',
            field=models.BooleanField(default=False),
        ),
    ]
