# Generated by Django 5.0.6 on 2024-09-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0009_paymentdetailsgroup_deposit_number_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetailsgroup',
            name='bic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
