# Generated by Django 5.0.6 on 2024-09-08 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0010_paymentdetailsgroup_bic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='deposit_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_deposit_number', message='Enter a valid deposit number', regex='^\\d{20}$')]),
        ),
    ]
