# Generated by Django 5.0.6 on 2024-09-09 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0011_alter_paymentdetails_deposit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetailsgroup',
            name='bic',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(code='invalid_bic', message='Enter a valid BIC', regex='^\\d{9}$')]),
        ),
    ]
