# Generated by Django 5.0.6 on 2024-09-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0012_alter_paymentdetailsgroup_bic'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentdetails',
            name='unique_active_deposit_number_per_group',
        ),
        migrations.AddConstraint(
            model_name='paymentdetails',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('deposit_number',), name='unique_active_deposit_number_per_group'),
        ),
        migrations.AddConstraint(
            model_name='paymentdetails',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('phone',), name='unique_active_phone'),
        ),
        migrations.AddConstraint(
            model_name='paymentdetails',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('card_number',), name='unique_active_card_number'),
        ),
    ]
