# Generated by Django 5.0.6 on 2024-09-09 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0013_remove_paymentdetails_unique_active_deposit_number_per_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(code='invalid_card_number', message='Enter a valid card number in format of 16 digits', regex='^\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number', regex='^\\+79\\d{9}$')]),
        ),
    ]
