# Generated by Django 5.0.6 on 2024-09-14 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0014_alter_paymentdetails_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetailsgroup',
            name='auto_live',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentdetailsgroup',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
