# Generated by Django 5.0.6 on 2024-09-24 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0015_paymentdetailsgroup_auto_live_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetailsgroup',
            name='work_type',
            field=models.CharField(blank=True, choices=[('by_card', 'Card'), ('by_cash', 'Cash'), ('by_deposit_number', 'Deposit Number')], default='by_card', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='traderteam',
            name='insurance_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='paymentdetailsgroup',
            name='status',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
