# Generated by Django 5.0.6 on 2024-09-24 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0016_paymentdetailsgroup_work_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetailsgroup',
            name='status',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
