# Generated by Django 5.0.6 on 2024-09-24 22:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0017_alter_paymentdetailsgroup_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderTeamRates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mdr_in', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mdr_out', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics.traderteam')),
            ],
        ),
    ]
