# Generated by Django 5.0.6 on 2024-09-25 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0018_traderteamrates'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderteamrates',
            name='payment_system',
            field=models.ForeignKey(default='cf2f5db2-4cdb-4309-8391-7c07a279d030', on_delete=django.db.models.deletion.CASCADE, to='basics.paymentsystem'),
            preserve_default=False,
        ),
    ]
