# Generated by Django 5.0.6 on 2024-09-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0019_traderteamrates_payment_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetailsgroup',
            name='auto_live',
            field=models.DateTimeField(default=0),
        ),
    ]
