# Generated by Django 5.0.6 on 2024-07-07 22:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basics', '0001_initial'),
        ('merchant', '0001_initial'),
        ('sms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InOrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='New', max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutOrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='New', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('address_public', models.CharField(default='', max_length=42)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='basics.balance')),
            ],
        ),
        migrations.CreateModel(
            name='InOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('completion_date', models.DateTimeField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('usd_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('arbitrage_comment', models.CharField(max_length=63)),
                ('merchant_order_id', models.CharField(default='', max_length=256)),
                ('pic', models.URLField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('merchant_fee', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('trader_fee', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('recalculated', models.BooleanField(default=False)),
                ('auto_closed', models.BooleanField(default=False)),
                ('payment_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inorders', to='basics.paymentdetails')),
                ('sms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inorder', to='sms.sms')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchantsolution')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.inorderstatus')),
            ],
        ),
        migrations.CreateModel(
            name='InOrderStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedelta', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_change', to='trade.inorder')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='change', to='trade.inorderstatus')),
            ],
        ),
        migrations.CreateModel(
            name='OutOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('first_creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('rejection_reason', models.CharField(blank=True, choices=[('wrong_reqs', 'Wrong Requisites'), ('red_scr', 'Red Screen')], max_length=10, null=True)),
                ('completion_date', models.DateTimeField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('usd_amount', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('destination_details', models.JSONField(default=dict)),
                ('merchant_order_id', models.CharField(default='', max_length=255)),
                ('pic', models.URLField()),
                ('merchant_fee', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('trader_fee', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('recalculated', models.BooleanField(default=False)),
                ('auto_closed', models.BooleanField(default=False)),
                ('payment_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outorders', to='basics.paymentdetails')),
                ('previous_orders', models.ManyToManyField(to='trade.outorder')),
                ('sms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outorder', to='sms.sms')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.merchantsolution')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.outorderstatus')),
            ],
        ),
        migrations.CreateModel(
            name='OutOrderStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedelta', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_change', to='trade.outorder')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='change', to='trade.outorderstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comment', models.CharField(default='-', editable=False, max_length=256)),
                ('value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('from_balance', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcoming_transactions', to='basics.balance')),
                ('linked_in_order', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.inorder')),
                ('linked_out_order', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.outorder')),
                ('to_balance', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='basics.balance')),
                ('transaction_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.transactiontype')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('address_to', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=256)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('balance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basics.balance')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
