# Generated by Django 5.0.6 on 2024-07-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outorder',
            name='pdf_comment',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outorder',
            name='pdf_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outorder',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
