# Generated by Django 5.0.6 on 2024-09-06 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_outorder_pdf_comment_outorder_pdf_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inorder',
            name='recalculated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='outorder',
            name='recalculated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
