# Generated by Django 5.0.6 on 2024-09-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_inorder_recalculated_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inorder',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('no-pay', 'No payment'), ('inc-check', 'Incorrect check'), ('wr-req', 'Wrong reqs'), ('wr-dir', 'Wrong SBP direction')], max_length=10, null=True),
        ),
    ]
